apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: node-web-app-stg
spec:
  generators:
  - git:
      files:
      - path: deployments/aws-stg/**/config.yaml
      repoURL: https://github.ibm.com/automation-paas-cd-pipeline/cloudrock-cicd-poc.git
      revision: HEAD
  template:
    metadata:
      labels:
        cloud: aws
        environment: staging
        instance: '{{ instance.id }}'
        region: '{{ region }}'
      name: node-web-app-{{instance.id}}
    spec:
      destination:
        namespace: '{{ cluster.namespace }}'
        server: '{{ cluster.url }}'
      ignoreDifferences:
      - jqPathExpressions:
        - .imagePullSecrets[] | select(.name | contains("dockercfg"))
        kind: ServiceAccount
      project: cicd
      source:
        path: resources
        plugin:
          env:
          - name: HELM_VALUES
            value: --values values-stg.yaml
          - name: HELM_ARGS
            value: --set instance.crn={{ instance.crn }},instance.createdAt={{ instance.createdAt
              }},server={{ cluster.url }},namespace={{ cluster.namespace }},region={{
              region }}
          name: argocd-vault-plugin-helm
        repoURL: https://github.ibm.com/automation-paas-cd-pipeline/cloudrock-cicd-poc.git
        targetRevision: deaceedf8d2d763b907c92b8adea3eba4fdee666