apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: asp-cicd-appset-stg
spec:
  generators:
  - git:
      files:
      - path: resources/configurations/aws-stg/**/**/cluster-config.yaml
      repoURL: https://github.ibm.com/automation-paas-cd-pipeline/mcsp-argocd-poc.git
      revision: HEAD
  template:
    metadata:
      annotations:
        notifications.argoproj.io/subscribe.on-health-degraded.workspace1: C0251PZR7K8
        notifications.argoproj.io/subscribe.on-sync-failed.workspace1: C0251PZR7K8
        notifications.argoproj.io/subscribe.on-sync-running.workspace1: C0251PZR7K8
        notifications.argoproj.io/subscribe.on-sync-status-unknown.workspace1: C0251PZR7K8
        notifications.argoproj.io/subscribe.on-sync-succeeded.workspace1: C0251PZR7K8
      labels:
        cloud: aws
        environment: staging
        instance: '{{ instance.id }}'
        region: '{{ region }}'
      name: node-web-app-{{instance.id}}
    spec:
      destination:
        namespace: '{{ cluster.namespace }}'
        server: '{{ cluster.url }}'
      ignoreDifferences:
      - jqPathExpressions:
        - .imagePullSecrets[] | select(.name | contains("dockercfg"))
        kind: ServiceAccount
      project: cloudrock-cicd
      source:
        path: resources
        plugin:
          env:
          - name: HELM_VALUES
            value: --values values.yaml --values configurations/aws-stg/environment-config.yaml
          - name: HELM_ARGS
            value: --set server={{ cluster.url }},namespace={{ cluster.namespace }},host={{ cluster.host }}
          - name: AVP_SECRET
            value: argocd-aws-test-asp-credentials
          name: argocd-vault-plugin-helm-custom
        repoURL: https://github.ibm.com/automation-paas-cd-pipeline/mcsp-argocd-poc.git
        targetRevision: v2024-03-19_01-56-14-9269ef0
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
          limit: 3
        syncOptions:
        - CreateNamespace=true
