application: node-web-app-preprod
applicationSetPath: application-sets/aws-preprod/app-set.yaml
clusterRoleBinding: cicd-crb-preprod
containerPort: 8080
deploymentPromoterSecret: cicd-dp-secret-preprod
environment: development
githubBranch: main
host: 0.0.0.0
image: sfonseca95/dockerized-node-js:latest
imagePullSecret: cicd-ips-preprod
port: 80
promotionEnvironment: production
replacements: "resources/values/values-preprod.yaml replacementExample1:new-value-1;resources/values/values-preprod.yaml replacementExample2:new-value-2;resources/values/values-preprod.yaml replacementExample3:new-value-3"
replacementExample1: value-1
replacementExample2: value-2
replacementExample3: value-3
serviceAccount: cicd-sa-preprod
testRunnerSecret: cicd-tr-secret-preprod
version: 1.2.0