application: node-web-app-stg
clusterRoleBinding: cicd-crb-stg
containerPort: 8080
deploymentPromoterSecret: cicd-dp-secret-stg
environment: development
githubBranch: main
host: 0.0.0.0
image: us.icr.io/cloudrock_cicd/dockerized-node-js:v1.0
imagePullSecret: cicd-ips-stg
port: 80
promotionEnv: pre-production
promotionEnvAppSet: application-sets/aws-preprod/app-set.yaml
replacements: "resources/values/values-stg.yaml image,us.icr.io/cloudrock_cicd/dockerized-node-js:v1.1"
serviceAccount: cicd-sa-stg
testList: https://raw.github.ibm.com/automation-saas/CICD-Test-Configuration/main/test-list-samples/success-tests.json?token=AABTMOJFKZOOF6UDZ6GGOBDCBNEH2
testListTags: sample
testRunnerSecret: cicd-tr-secret-stg
version: 1.2.0