application: node-web-app-dev
containerPort: 8080
environment: development
host: 0.0.0.0
image: us.icr.io/cloudrock_cicd/dockerized-node-js:latest
port: 80
replacementExample1: value-1
replacementExample2: value-2
replacementExample3: value-3
trClusterRoleBinding: cicd-tr-crb-dev
trImagePullSecret: cicd-tr-ps-dev
trSecret: cicd-tr-secret-dev
trServiceAccount: cicd-tr-sa-dev
version: 1.2.0