application: node-web-app
changeRequestCreatorSecret: cicd-cr-secret
deploymentPromoterSecret: cicd-dp-secret
domain: automation.cloud.ibm.com
image: ''
imagePullSecret: cicd-ips
role: cicd-role
roleBinding: cicd-rb
secrets:
  artifactory: <artifactory-token | base64encode>
  deploymentPromoterParameters: <path:automation-saas-platform/cicd/deployment-promoter-parameters#github-token | base64encode>
  dockerconfigjson: <path:automation-saas-platform/cicd/global-dockerconfigjson#dockerconfigjson | base64encode>
  github: <github-token | base64encode>
  changeRequestCreatorParameters: <path:multicloud-saas-platform/cicd/salesforce-parameters#SRE_CONSOLE_API_KEY | base64encode>
  slack: <slack-token | base64encode>
  testRunnerParameters: automation-saas-platform/cicd/test-runner-parameters
serviceAccount: cicd-sa
testRunnerSecret: cicd-tr-secret
version: 1.2.5

environment: development # default value
