application: node-web-app
version: 1.1.9
port: 80
host: 0.0.0.0
containerPort: 8080
trImagePullSecret: test-runner-ps
trSecret: test-runner-secret
trServiceAccount: test-runner-sa
trClusterRoleBinding: test-runner-crb