application: node-web-app
clusterRoleBinding: cicd-crb
deploymentPromoterSecret: cicd-dp-secret
image: icr.io/automation-saas-platform/cicd/cloudrock-ci-poc:20220517032336-1425_test-21c22fd008d44b7edb31e2e0e1b6819af7f376b3
imagePullSecret: cicd-ips
serviceAccount: cicd-sa
testRunnerSecret: cicd-tr-secret
version: 1.2.0
