application: node-web-app
clusterRoleBinding: cicd-crb
deploymentPromoterSecret: cicd-dp-secret
image: us.icr.io/cloudrock_cicd/dockerized-node-js:v1.1
imagePullSecret: cicd-ips
serviceAccount: cicd-sa
testRunnerSecret: cicd-tr-secret
version: 1.2.0
