application: node-web-app
clusterRoleBinding: cicd-crb
deploymentPromoterSecret: cicd-dp-secret
image: icr.io/automation-saas-platform/cicd/dockerized-node-js:v1.0
imagePullSecret: cicd-ips
serviceAccount: cicd-sa
testRunnerSecret: cicd-tr-secret
version: 1.2.0