application: node-web-app
clusterRoleBinding: cicd-crb
deploymentPromoterSecret: cicd-dp-secret
image: icr.io/automation-saas-platform/cicd/cloudrock-ci-poc:20220523224645-main-c23fe52b44be2bca3a597a2cba1d76ebff783181
imagePullSecret: cicd-ips
serviceAccount: cicd-sa
testRunnerSecret: cicd-tr-secret
version: 1.2.0
