application: node-web-app-dev
version: 1.2.0
port: 80
host: 0.0.0.0
containerPort: 8080
environment: development
trImagePullSecret: cicd-tr-ps-dev
trSecret: cicd-tr-secret-dev
trServiceAccount: cicd-tr-sa-dev
trClusterRoleBinding: cicd-tr-crb-dev