application: node-web-app
role: cicd-role
roleBinding: cicd-rb
deploymentPromoterSecret: cicd-dp-secret
domain: automation.cloud.ibm.com
image: icr.io/automation-saas-platform/cicd/cloudrock-ci-poc:20220523224645-main-c23fe52b44be2bca3a597a2cba1d76ebff783181
imagePullSecret: cicd-ips
serviceAccount: cicd-sa
secrets:
  artifactory: "<artifactory-token | base64encode>"
  deploymentPromoterParameters: "<path:automation-saas-platform/cicd/deployment-promoter-parameters#github-token | base64encode>"
  dockerconfigjson: "<path:automation-saas-platform/cicd/global-dockerconfigjson#dockerconfigjson | base64encode>"
  github: "<github-token | base64encode>"
  testRunnerParameters: "automation-saas-platform/cicd/test-runner-parameters"
  slack: "<slack-token | base64encode>"
testRunnerSecret: cicd-tr-secret
version: 1.2.0
