region: us-east
prebindingId: pre-sr7o1558-044c-99bc-4e3c-65g5e7641fj6
instance:
  id: gh56ce02-4b67-800f-4b0c-4578612k4m9k
  name: node-web-app
  crn: "placeholder"
  createdAt: '1633366800000' 
cluster:
  id: 67a657d9-ecec-4857-8617-484e1f223578
  url: https://api.dp-argocd-rosa.harl.p1.openshiftapps.com:6443
  namespace: node-web-app-4
  host: node-web-app-service-node-web-app-4.apps.dp-argocd-rosa.harl.p1.openshiftapps.com