region: us-east
prebindingId: pre-jn7o1558-022c-56ac-4e3c-32g5e5641fg6
instance:
  id: op89ce02-6b56-500f-4b0c-3414612k4m9j
  name: node-web-app
  crn: "placeholder"
  createdAt: '1633366800000' 
cluster:
  id: 85a657d9-ecec-4857-8617-484e1f223527
  url: https://api.cp-argocd-rosa.dnco.p1.openshiftapps.com:6443
  namespace: node-web-app-1
  host: node-web-app-service-node-web-app-1.apps.cp-argocd-rosa.dnco.p1.openshiftapps.com