awsToken: aws-token
environment: pre-production
previousEnvAppSet: application-sets/aws-stg/application-set.yaml
promotionEnv: production
promotionEnvAppSet: application-sets/aws-prod/application-set.yaml