apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data: 
  .dockerconfigjson: <path:cloudrock/cicd/global-dockerconfigjson#cloudrock/cicd/global-dockerconfigjson | base64encode>
type: kubernetes.io/dockerconfigjson