################################################################
# Licensed Materials - Property of IBM
# Automation PaaS - Service account for Argo CD
# Copyright IBM Corporation 2021, 2022. All Rights Reserved.
# U.S. Government Users Restricted Rights:
# Use, duplication, or disclosure restricted by IBM Corporation.
################################################################

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
imagePullSecrets:
- name: {{ .Values.imagePullSecret }}