apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application }}-service
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: {{ .Values.application }}