apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.application }}-deployment
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  selector:
    matchLabels:
      app: {{ .Values.application }}
  replicas: 3
  template:
    metadata:
      labels:
        app: {{ .Values.application }}
        version: {{ .Values.version }}
    spec:
      containers:
      - name: {{ .Values.application }}
        image: {{ .Values.image }}
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: {{ .Values.application }}-config
        ports:
        - containerPort: {{ .Values.containerPort }}