apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: "{{ .Values.application }}-route-{{ .Values.environment }}"
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  host: {{ .Values.host }}
  to:
    kind: Service
    name: {{ .Values.application }}-service
    weight: 100