{{ if not (contains "prod" .Values.environment) }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.application }}-service-{{ .Values.environment }}"
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: {{ .Values.application }}
{{ end }}