apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application }}-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.containerPort }}
  selector:
    app: {{ .Values.application }}