apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: node-web-app-dev
spec:
  generators:
  - git:
      files:
      - path: applications/configurations/aws-dev/**/cluster-config.yaml
      repoURL: https://github.ibm.com/automation-paas-cd-pipeline/cloudrock-cicd-poc.git
      revision: HEAD
  template:
    metadata:
      labels:
        cloud: aws
        environment: development
        instance: '{{ instance.id }}'
        region: '{{ region }}'
      name: node-web-app-{{instance.id}}
    spec:
      destination:
        namespace: '{{ cluster.namespace }}'
        server: '{{ cluster.url }}'
      ignoreDifferences:
      - jqPathExpressions:
        - .imagePullSecrets[] | select(.name | contains("dockercfg"))
        kind: ServiceAccount
      project: cicd
      source:
        path: applications
        plugin:
          env:
          - name: HELM_VALUES
            value: --values values.yaml  --values configurations/aws-dev/environment-config.yaml
          - name: HELM_ARGS
            value: --set example=example
          name: argocd-vault-plugin-helm
        repoURL: https://github.ibm.com/automation-paas-cd-pipeline/cloudrock-cicd-poc.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true