apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: node-web-app-set-dev
spec:
  generators:
  - git:
      files:
      - path: resources/configurations/aws-dev/**/cluster-config.yaml
      repoURL: https://github.ibm.com/automation-paas-cd-pipeline/cloudrock-argocd-poc.git
      revision: HEAD
  template:
    metadata:
      labels:
        cloud: aws
        environment: development
        instance: '{{ instance.id }}'
        region: '{{ region }}'
      name: node-web-app-dev-{{instance.id}}
    spec:
      destination:
        namespace: '{{ cluster.namespace }}'
        server: '{{ cluster.url }}'
      ignoreDifferences:
      - jqPathExpressions:
        - .imagePullSecrets[] | select(.name | contains("dockercfg"))
        kind: ServiceAccount
      project: cicd
      source:
        path: resources
        plugin:
          env:
          - name: HELM_VALUES
            value: --values values.yaml --values configurations/aws-dev/environment-config.yaml
          - name: HELM_ARGS
            value: --set server={{ cluster.url }},namespace={{ cluster.namespace }},host={{ cluster.host }},targetRevision=$ARGOCD_APP_REVISION
          name: argocd-vault-plugin-helm
        repoURL: https://github.ibm.com/automation-paas-cd-pipeline/cloudrock-argocd-poc.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        retry:
            limit: 3
            backoff:
              duration: 5s 
              factor: 2
              maxDuration: 3m 