################################################################
# Licensed Materials - Property of IBM
# Automation PaaS - Secrets associated with validation tests 
#                   using the Test Runner
# Copyright IBM Corporation 2022. All Rights Reserved.
# U.S. Government Users Restricted Rights:
# Use, duplication, or disclosure restricted by IBM Corporation.
################################################################

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.trSecret }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
data:
  ARTIFACTORY_TOKEN: <path:cloudrock/cicd/artifactory-token#cloudrock/cicd/artifactory-token | base64encode>
  CLUSTER_API_KEY: <path:cloudrock/cicd/aws-token#cloudrock/cicd/aws-token | base64encode>
  GITHUB_TOKEN: <path:cloudrock/cicd/github-token#cloudrock/cicd/github-token | base64encode>
  SLACK_TOKEN: <path:cloudrock/cicd/slack-token#cloudrock/cicd/slack-token | base64encode>
stringData:
  CLUSTER_TYPE: "OpenShift"
  TEST_LIST: "https://raw.github.ibm.com/automation-saas/CICD-Test-Configuration/main/test-list-samples/success-tests.json?token=AABTMOOICUDNBOWIZLZWRZ3CBCJPS"
  TEST_LIST_TAGS: "sample"
  TEST_POD_SERVICE_ACCOUNT: {{ .Values.trServiceAccount }}
  TEST_POD_NAMESPACE: {{ .Values.namespace }}
  NAMESPACE: {{ .Values.namespace }}
  SERVER: {{ .Values.server }}
  REPORT_ON_ERROR: "True"
  ARTIFACTORY_FUNC_ID: "sujeily.fonseca@ibm.com"
  ARTIFACTORY_REGISTRY: "https://na.artifactory.swg-devops.com/artifactory/ccs-cloudrock-team-generic-local/"
  GITHUB_ORG: "automation-saas"
  GITHUB_REPO: "automation-test"
  ISSUE_ASSIGNEES_STR: "sujeily-fonseca"
  ISSUE_LABELS_STR: "Squad: CICD"
  SLACK_CHANNEL: "C0251PZR7K8"