{{ if not (contains "prod" .Values.environment) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.changeRequestCreatorSecret }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
data:
  SRE_CONSOLE_API_KEY: {{ .Values.secrets.changeRequestCreatorParameters }}
{{ end }}