{{ if not (contains "prod" .Values.environment) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.changeRequestCreatorSecret }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
data:
  SRE_CONSOLE_API_KEY: {{ .Values.secrets.changeRequestCreatorParameters }}
stringData:
  SRE_CONSOLE_API_BASE_URL: "https://sre-console-api.platform.test.saas.ibm.com/sre-console/srebackend"
{{ end }}