{{ if not (contains "prod" .Values.environment) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.deploymentPromoterSecret }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
data:
  GITHUB_TOKEN: {{ .Values.secrets.deploymentPromoterParameters }}
stringData:
  ENABLE_DEV_HEAD_USE: "True"
  GITHUB_BRANCH: "main"
  GITHUB_COMMITTER: "CI/CD Functional ID <autopaas@us.ibm.com>"
  GITHUB_ORG: "automation-paas-cd-pipeline"
  GITHUB_REPO: "https://github.ibm.com/automation-paas-cd-pipeline/mcsp-argocd-poc.git"
  PREVIOUS_ENV_APP_SET: {{ .Values.previousEnvAppSet }}
  PROMOTION_ENV: "abcd"
  PROMOTION_ENV_APP_SET: "pqr"
  PULL_REQUEST_ASSIGNEES: "sujeily-fonseca"
{{ end }}
