apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.deploymentPromoterSecret }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
data:
  GITHUB_TOKEN: <path:cloudrock/cicd/github-token#cloudrock/cicd/github-token | base64encode>
stringData:
  GITHUB_BRANCH: {{ .Values.githubBranch }}
  GITHUB_COMMITTER: "CI/CD Functional ID <autopaas@us.ibm.com>"
  GITHUB_ORG: "automation-paas-cd-pipeline"
  GITHUB_REPO: "https://github.ibm.com/automation-paas-cd-pipeline/cloudrock-cicd-poc.git"
  REPLACEMENTS: {{ .Values.replacements }}
  PROMOTION_ENV: {{ .Values.promotionEnv }}
  PROMOTION_ENV_APP_SET: {{ .Values.promotionEnvAppSet }}
  PULL_REQUEST_ASSIGNEES: "sujeily-fonseca"