apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.deploymentPromoterSecret }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
data:
  GITHUB_TOKEN: <path:cloudrock/cicd/github-token#cloudrock/cicd/github-token | base64encode>
stringData:
  DEVELOPMENT_ENV_APP_SET: "application-sets/aws-dev/application-set.yaml"
  ENABLE_DEV_HEAD_USE: "True"
  GITHUB_BRANCH: "main"
  GITHUB_COMMITTER: "CI/CD Functional ID <autopaas@us.ibm.com>"
  GITHUB_ORG: "automation-paas-cd-pipeline"
  GITHUB_REPO: "https://github.ibm.com/automation-paas-cd-pipeline/cloudrock-argocd-poc.git"
  PREVIOUS_ENV_APP_SET: {{ .Values.previousEnvAppSet }}
  PROMOTION_ENV: {{ .Values.promotionEnv }}
  PROMOTION_ENV_APP_SET: {{ .Values.promotionEnvAppSet }}
  PULL_REQUEST_ASSIGNEES: "sujeily-fonseca"