region: us-east
prebindingId: pre-zx7o1558-077c-88bc-3w3c-56g5e7641f9o
instance:
  id: ba54ce02-3a67-600f-7b9c-3478612k4muh
  name: node-web-app
  crn: "placeholder"
  createdAt: '1633366800000' 
cluster:
  id: 67a657d9-ecec-4857-8617-484e1f223578
  url: https://api.dp-argocd-rosa.harl.p1.openshiftapps.com:6443
  namespace: node-web-app-3
