apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.testRunnerSecret }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
data:
  ARTIFACTORY_TOKEN: <path:cloudrock/cicd/artifactory-token#cloudrock/cicd/artifactory-token | base64encode>
  GITHUB_TOKEN: <path:cloudrock/cicd/github-token#cloudrock/cicd/github-token | base64encode>
  SLACK_TOKEN: <path:cloudrock/cicd/slack-token#cloudrock/cicd/slack-token | base64encode>
stringData:
  LOAD_INCLUSTER_CONFIG: "True"
  TEST_LIST_PATH: "test-list-samples/success-tests.json"
  TEST_LIST_REPO: "https://github.ibm.com/automation-saas/CICD-Test-Configuration.git"
  TEST_LIST_REVISION: "main"
  TEST_LIST_TAGS: "sample"
  TEST_POD_SERVICE_ACCOUNT: "test-runner-sa"
  TEST_POD_NAMESPACE: "cicd-test-runner"
  SERVER: "https://api.dp-argocd-rosa.harl.p1.openshiftapps.com:6443"
  REPORT_ON_ERROR: "True"
  ARTIFACTORY_FUNC_ID: "sujeily.fonseca@ibm.com"
  ARTIFACTORY_REGISTRY: "https://na.artifactory.swg-devops.com/artifactory/ccs-cloudrock-team-generic-local/"
  GITHUB_ORG: "automation-saas"
  GITHUB_REPO: "automation-test"
  ISSUE_ASSIGNEES_STR: "sujeily-fonseca"
  ISSUE_LABELS_STR: "Squad: CICD"
  SLACK_CHANNEL: "C0251PZR7K8"
