{{ if not (contains "prod" .Values.environment) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.testRunnerSecret }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    avp.kubernetes.io/path: {{ .Values.secrets.testRunnerParameters }}
type: Opaque
data:
  ARTIFACTORY_TOKEN: {{ .Values.secrets.artifactory }}
  SLACK_TOKEN: {{ .Values.secrets.slack }}
stringData:
  LOAD_INCLUSTER_CONFIG: "True"
  TEST_LIST_PATH: "test-list-samples/success-tests.json"
  TEST_LIST_REPO: "https://github.ibm.com/ibm-saas-platform/CICD-Test-Configuration.git"
  TEST_LIST_REVISION: "main"
  TEST_LIST_TAGS: "sample"
  TEST_POD_SERVICE_ACCOUNT: {{ .Values.serviceAccount }}
  TEST_POD_NAMESPACE:  {{ .Values.namespace }}
  SERVER: {{ .Values.server }}
  REPORT_ON_ERROR: "True"
  ARTIFACTORY_FUNC_ID: "sujeily.fonseca@ibm.com"
  ARTIFACTORY_REGISTRY: "https://na.artifactory.swg-devops.com/artifactory/ccs-cloudrock-team-generic-local/"
  GITHUB_ORG: "automation-saas"
  GITHUB_REPO: "automation-test"
  ISSUE_ASSIGNEES_STR: "sujeily-fonseca"
  ISSUE_LABELS_STR: "Squad: CICD"
  SLACK_CHANNEL: "C0251PZR7K8"
{{ end }}
