apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.testRunnerSecret }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
data:
  ARTIFACTORY_TOKEN: <path:cloudrock/cicd/artifactory-token#cloudrock/cicd/artifactory-token | base64encode>
  CLUSTER_API_KEY: <path:cloudrock/cicd/aws-token#cloudrock/cicd/aws-token | base64encode>
  GITHUB_TOKEN: <path:cloudrock/cicd/github-token#cloudrock/cicd/github-token | base64encode>
  SLACK_TOKEN: <path:cloudrock/cicd/slack-token#cloudrock/cicd/slack-token | base64encode>
stringData:
  CLUSTER_TYPE: "OpenShift"
  TEST_LIST: {{ .Values.testList }}
  TEST_LIST_TAGS: {{ .Values.testListTags }}
  TEST_POD_SERVICE_ACCOUNT: {{ .Values.serviceAccount }}
  TEST_POD_NAMESPACE: {{ .Values.namespace }}
  NAMESPACE: {{ .Values.namespace }}
  SERVER: {{ .Values.server }}
  REPORT_ON_ERROR: "True"
  ARTIFACTORY_FUNC_ID: "sujeily.fonseca@ibm.com"
  ARTIFACTORY_REGISTRY: "https://na.artifactory.swg-devops.com/artifactory/ccs-cloudrock-team-generic-local/"
  GITHUB_ORG: "automation-saas"
  GITHUB_REPO: "automation-test"
  ISSUE_ASSIGNEES_STR: "sujeily-fonseca"
  ISSUE_LABELS_STR: "Squad: CICD"
  SLACK_CHANNEL: "C0251PZR7K8"