################################################################
# Licensed Materials - Property of IBM
# Automation PaaS - Cluster role binding for Argo CD
# Copyright IBM Corporation 2021, 2022. All Rights Reserved.
# U.S. Government Users Restricted Rights:
# Use, duplication, or disclosure restricted by IBM Corporation.
################################################################

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.trClusterRoleBinding }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
subjects:
  - kind: ServiceAccount
    name: {{ .Values.trServiceAccount }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io