################################################################
# Licensed Materials - Property of IBM
# Automation PaaS - Test Runner for Argo CD
# Copyright IBM Corporation 2022. All Rights Reserved.
# U.S. Government Users Restricted Rights:
# Use, duplication, or disclosure restricted by IBM Corporation.
################################################################

apiVersion: batch/v1
kind: Job
metadata:
  generateName: test-runner-
  namespace: {{ .Values.namespace }}
  labels:
    type: host
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: {{ .Values.trServiceAccount }}
      automountServiceAccountToken: false
      restartPolicy: Never
      containers:
        - name: test-runner-container
          image: us.icr.io/cloudrock_cicd/test-runner:stable
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: {{ .Values.trSecret }}
          resources:
            limits:
              cpu: "500m"
            requests:
              cpu: "250m"
  parallelism: 1
  backoffLimit: 0