{{ if not (contains "prod" .Values.environment) }}
apiVersion: batch/v1
kind: Job
metadata:
  generateName: test-runner-
  namespace: {{ .Values.namespace }}
  labels:
    type: host
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "10"
spec:
  template:
    spec:
      serviceAccountName: {{ .Values.serviceAccount }}
      automountServiceAccountToken: false
      restartPolicy: Never
      containers:
        - name: test-runner-container
          image: icr.io/automation-saas-platform/cicd/test-runner:stable
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: {{ .Values.testRunnerSecret }}
          resources:
            limits:
              cpu: "500m"
            requests:
              cpu: "250m"
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            privileged: false
            runAsNonRoot: true
            runAsUser: 1000750000
            capabilities:
              drop:
              - ALL
  parallelism: 1
  backoffLimit: 0
{{ end }}
